<?php
namespace App\Controller;
use App\Controller\AppController;
use Cake\Datasource\ConnectionManager;
use Cake\ORM\TableRegistry;

class DbController extends AppController{
    private $connection;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->connection=ConnectionManager::get('default');
        $this->viewBuilder()->setLayout('index');
        $this->loadModel('Departments');
        

    }

    public function insertDepartment()

    {
        $this->autoRender=false;
        $department=$this->Departments->newEntity();
        $department->name="Software Engineering";
        $department->hod="Touhid";
        $department->phone="23893298";
        $this->Departments->save($department);

    }

    public function getDepartment()
    {
        $this->autoRender=false;
        $dept=$this->Departments->find();

        foreach ($dept as $d){
            echo $d;
        }
    }

    public function insert()
    {
        $this->connection->insert('students',[
            'name'=>'Ringku',
            'email'=>'r@email.com',
            'department'=>'swe'
        ]);

    }

    public function show()
    {
        $this->autoRender=false;
     $data = $this->connection->exicute("SELECT * FROM students")->fetchAll()->toArray();

         print_r($data);

    }

    public function update()
    {
        $this->connection->update('students',[
            'email'=>'ringku.mmj@gmail.com'
        ],
            [
             'id'=>1
            ]);
    }

    public function index()
    {
        echo "some";
    }
}

?>
